# for etcd
etcd_endpoints:
  - 127.0.0.1:2379
  - 127.0.0.1:2380
etcd_path: /config/nsq_consumer/default
etcd_username: root
etcd_password: root

# for elasticsearch
elastic_http_addrs:
  - 127.0.0.1:9200
  - 127.0.0.1:9201
elastic_username: root
elastic_password: 123456
elastic_index_name: nsq-%Y.%m.%d
elastic_index_type: nsq
