name: goreleaser

on:
  push:
    tags:
      - v*

job:
  goreleaser:
    runs-on: ubuntu-latest
    setps:
      - name: Checkout
        uses: actions/checkout@2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.goreleaser }}
